# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_auto_20171201_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='duration',
        ),
        migrations.AddField(
            model_name='workshop',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
